//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace DoCRM.wsSkyRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsSkySoapBinding", Namespace="www.sky3a.hiware.ru")]
    public partial class wsSky : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback fTicketListPageOperationCompleted;
        
        private System.Threading.SendOrPostCallback fTicketShowOperationCompleted;
        
        private System.Threading.SendOrPostCallback fServiceListPageOperationCompleted;
        
        private System.Threading.SendOrPostCallback fServiceShowOperationCompleted;
        
        private System.Threading.SendOrPostCallback fServiceEditOperationCompleted;
        
        private System.Threading.SendOrPostCallback fAnyActionOperationCompleted;
        
        private System.Threading.SendOrPostCallback fShowUserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback fCheckUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback fPacientListPageOperationCompleted;
        
        private System.Threading.SendOrPostCallback fTemplateShowOperationCompleted;
        
        private System.Threading.SendOrPostCallback fTamplateListPage1OperationCompleted;
        
        private System.Threading.SendOrPostCallback fObjectListPageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsSky() {
            this.Url = global::DoCRM.Properties.Settings.Default.WebApplication1_wsSky_wsSky;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event fTicketListPageCompletedEventHandler fTicketListPageCompleted;
        
        /// <remarks/>
        public event fTicketShowCompletedEventHandler fTicketShowCompleted;
        
        /// <remarks/>
        public event fServiceListPageCompletedEventHandler fServiceListPageCompleted;
        
        /// <remarks/>
        public event fServiceShowCompletedEventHandler fServiceShowCompleted;
        
        /// <remarks/>
        public event fServiceEditCompletedEventHandler fServiceEditCompleted;
        
        /// <remarks/>
        public event fAnyActionCompletedEventHandler fAnyActionCompleted;
        
        /// <remarks/>
        public event fShowUserInfoCompletedEventHandler fShowUserInfoCompleted;
        
        /// <remarks/>
        public event fCheckUserCompletedEventHandler fCheckUserCompleted;
        
        /// <remarks/>
        public event fPacientListPageCompletedEventHandler fPacientListPageCompleted;
        
        /// <remarks/>
        public event fTemplateShowCompletedEventHandler fTemplateShowCompleted;
        
        /// <remarks/>
        public event fTamplateListPage1CompletedEventHandler fTamplateListPage1Completed;
        
        /// <remarks/>
        public event fObjectListPageCompletedEventHandler fObjectListPageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.sky3a.hiware.ru#wsSky:fTicketListPage", RequestNamespace="www.sky3a.hiware.ru", ResponseNamespace="www.sky3a.hiware.ru", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public otTicketListPage fTicketListPage(string vUserRef, int vPageNum, int vRowsPerPage) {
            object[] results = this.Invoke("fTicketListPage", new object[] {
                        vUserRef,
                        vPageNum,
                        vRowsPerPage});
            return ((otTicketListPage)(results[0]));
        }
        
        /// <remarks/>
        public void fTicketListPageAsync(string vUserRef, int vPageNum, int vRowsPerPage) {
            this.fTicketListPageAsync(vUserRef, vPageNum, vRowsPerPage, null);
        }
        
        /// <remarks/>
        public void fTicketListPageAsync(string vUserRef, int vPageNum, int vRowsPerPage, object userState) {
            if ((this.fTicketListPageOperationCompleted == null)) {
                this.fTicketListPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfTicketListPageOperationCompleted);
            }
            this.InvokeAsync("fTicketListPage", new object[] {
                        vUserRef,
                        vPageNum,
                        vRowsPerPage}, this.fTicketListPageOperationCompleted, userState);
        }
        
        private void OnfTicketListPageOperationCompleted(object arg) {
            if ((this.fTicketListPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fTicketListPageCompleted(this, new fTicketListPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.sky3a.hiware.ru#wsSky:fTicketShow", RequestNamespace="www.sky3a.hiware.ru", ResponseNamespace="www.sky3a.hiware.ru", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public otTicketShow fTicketShow(string vUserRef, string vTicketRef) {
            object[] results = this.Invoke("fTicketShow", new object[] {
                        vUserRef,
                        vTicketRef});
            return ((otTicketShow)(results[0]));
        }
        
        /// <remarks/>
        public void fTicketShowAsync(string vUserRef, string vTicketRef) {
            this.fTicketShowAsync(vUserRef, vTicketRef, null);
        }
        
        /// <remarks/>
        public void fTicketShowAsync(string vUserRef, string vTicketRef, object userState) {
            if ((this.fTicketShowOperationCompleted == null)) {
                this.fTicketShowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfTicketShowOperationCompleted);
            }
            this.InvokeAsync("fTicketShow", new object[] {
                        vUserRef,
                        vTicketRef}, this.fTicketShowOperationCompleted, userState);
        }
        
        private void OnfTicketShowOperationCompleted(object arg) {
            if ((this.fTicketShowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fTicketShowCompleted(this, new fTicketShowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.sky3a.hiware.ru#wsSky:fServiceListPage", RequestNamespace="www.sky3a.hiware.ru", ResponseNamespace="www.sky3a.hiware.ru", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public otServiceListPage fServiceListPage(string vUserRef, int vPageNum, int vRowsPerPage, string vPacientRef, string vDate1, string vDate2) {
            object[] results = this.Invoke("fServiceListPage", new object[] {
                        vUserRef,
                        vPageNum,
                        vRowsPerPage,
                        vPacientRef,
                        vDate1,
                        vDate2});
            return ((otServiceListPage)(results[0]));
        }
        
        /// <remarks/>
        public void fServiceListPageAsync(string vUserRef, int vPageNum, int vRowsPerPage, string vPacientRef, string vDate1, string vDate2) {
            this.fServiceListPageAsync(vUserRef, vPageNum, vRowsPerPage, vPacientRef, vDate1, vDate2, null);
        }
        
        /// <remarks/>
        public void fServiceListPageAsync(string vUserRef, int vPageNum, int vRowsPerPage, string vPacientRef, string vDate1, string vDate2, object userState) {
            if ((this.fServiceListPageOperationCompleted == null)) {
                this.fServiceListPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfServiceListPageOperationCompleted);
            }
            this.InvokeAsync("fServiceListPage", new object[] {
                        vUserRef,
                        vPageNum,
                        vRowsPerPage,
                        vPacientRef,
                        vDate1,
                        vDate2}, this.fServiceListPageOperationCompleted, userState);
        }
        
        private void OnfServiceListPageOperationCompleted(object arg) {
            if ((this.fServiceListPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fServiceListPageCompleted(this, new fServiceListPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.sky3a.hiware.ru#wsSky:fServiceShow", RequestNamespace="www.sky3a.hiware.ru", ResponseNamespace="www.sky3a.hiware.ru", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public otServiceShow fServiceShow(string vUserRef, string vServiceRef) {
            object[] results = this.Invoke("fServiceShow", new object[] {
                        vUserRef,
                        vServiceRef});
            return ((otServiceShow)(results[0]));
        }
        
        /// <remarks/>
        public void fServiceShowAsync(string vUserRef, string vServiceRef) {
            this.fServiceShowAsync(vUserRef, vServiceRef, null);
        }
        
        /// <remarks/>
        public void fServiceShowAsync(string vUserRef, string vServiceRef, object userState) {
            if ((this.fServiceShowOperationCompleted == null)) {
                this.fServiceShowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfServiceShowOperationCompleted);
            }
            this.InvokeAsync("fServiceShow", new object[] {
                        vUserRef,
                        vServiceRef}, this.fServiceShowOperationCompleted, userState);
        }
        
        private void OnfServiceShowOperationCompleted(object arg) {
            if ((this.fServiceShowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fServiceShowCompleted(this, new fServiceShowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.sky3a.hiware.ru#wsSky:fServiceEdit", RequestNamespace="www.sky3a.hiware.ru", ResponseNamespace="www.sky3a.hiware.ru", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public otAnyActionResp fServiceEdit(string vUserRef, [System.Xml.Serialization.XmlArrayItemAttribute("prAnyActionParam", IsNullable=false)] otAnyActionParam[] vAnyActionParams, [System.Xml.Serialization.XmlArrayItemAttribute("prParamValueEdit", IsNullable=false)] otParamValueEdit[] vParamValuesEdit) {
            object[] results = this.Invoke("fServiceEdit", new object[] {
                        vUserRef,
                        vAnyActionParams,
                        vParamValuesEdit});
            return ((otAnyActionResp)(results[0]));
        }
        
        /// <remarks/>
        public void fServiceEditAsync(string vUserRef, otAnyActionParam[] vAnyActionParams, otParamValueEdit[] vParamValuesEdit) {
            this.fServiceEditAsync(vUserRef, vAnyActionParams, vParamValuesEdit, null);
        }
        
        /// <remarks/>
        public void fServiceEditAsync(string vUserRef, otAnyActionParam[] vAnyActionParams, otParamValueEdit[] vParamValuesEdit, object userState) {
            if ((this.fServiceEditOperationCompleted == null)) {
                this.fServiceEditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfServiceEditOperationCompleted);
            }
            this.InvokeAsync("fServiceEdit", new object[] {
                        vUserRef,
                        vAnyActionParams,
                        vParamValuesEdit}, this.fServiceEditOperationCompleted, userState);
        }
        
        private void OnfServiceEditOperationCompleted(object arg) {
            if ((this.fServiceEditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fServiceEditCompleted(this, new fServiceEditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.sky3a.hiware.ru#wsSky:fAnyAction", RequestNamespace="www.sky3a.hiware.ru", ResponseNamespace="www.sky3a.hiware.ru", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public otAnyActionResp fAnyAction(string vUserRef, otAnyActionData vAnyActionData) {
            object[] results = this.Invoke("fAnyAction", new object[] {
                        vUserRef,
                        vAnyActionData});
            return ((otAnyActionResp)(results[0]));
        }
        
        /// <remarks/>
        public void fAnyActionAsync(string vUserRef, otAnyActionData vAnyActionData) {
            this.fAnyActionAsync(vUserRef, vAnyActionData, null);
        }
        
        /// <remarks/>
        public void fAnyActionAsync(string vUserRef, otAnyActionData vAnyActionData, object userState) {
            if ((this.fAnyActionOperationCompleted == null)) {
                this.fAnyActionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfAnyActionOperationCompleted);
            }
            this.InvokeAsync("fAnyAction", new object[] {
                        vUserRef,
                        vAnyActionData}, this.fAnyActionOperationCompleted, userState);
        }
        
        private void OnfAnyActionOperationCompleted(object arg) {
            if ((this.fAnyActionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fAnyActionCompleted(this, new fAnyActionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.sky3a.hiware.ru#wsSky:fShowUserInfo", RequestNamespace="www.sky3a.hiware.ru", ResponseNamespace="www.sky3a.hiware.ru", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public otShowUserInfo fShowUserInfo(string vUserRef, string vCurPacientRef) {
            object[] results = this.Invoke("fShowUserInfo", new object[] {
                        vUserRef,
                        vCurPacientRef});
            return ((otShowUserInfo)(results[0]));
        }
        
        /// <remarks/>
        public void fShowUserInfoAsync(string vUserRef, string vCurPacientRef) {
            this.fShowUserInfoAsync(vUserRef, vCurPacientRef, null);
        }
        
        /// <remarks/>
        public void fShowUserInfoAsync(string vUserRef, string vCurPacientRef, object userState) {
            if ((this.fShowUserInfoOperationCompleted == null)) {
                this.fShowUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfShowUserInfoOperationCompleted);
            }
            this.InvokeAsync("fShowUserInfo", new object[] {
                        vUserRef,
                        vCurPacientRef}, this.fShowUserInfoOperationCompleted, userState);
        }
        
        private void OnfShowUserInfoOperationCompleted(object arg) {
            if ((this.fShowUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fShowUserInfoCompleted(this, new fShowUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.sky3a.hiware.ru#wsSky:fCheckUser", RequestNamespace="www.sky3a.hiware.ru", ResponseNamespace="www.sky3a.hiware.ru", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public otCheckUser fCheckUser(string vILogin, string vIPass) {
            object[] results = this.Invoke("fCheckUser", new object[] {
                        vILogin,
                        vIPass});
            return ((otCheckUser)(results[0]));
        }
        
        /// <remarks/>
        public void fCheckUserAsync(string vILogin, string vIPass) {
            this.fCheckUserAsync(vILogin, vIPass, null);
        }
        
        /// <remarks/>
        public void fCheckUserAsync(string vILogin, string vIPass, object userState) {
            if ((this.fCheckUserOperationCompleted == null)) {
                this.fCheckUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfCheckUserOperationCompleted);
            }
            this.InvokeAsync("fCheckUser", new object[] {
                        vILogin,
                        vIPass}, this.fCheckUserOperationCompleted, userState);
        }
        
        private void OnfCheckUserOperationCompleted(object arg) {
            if ((this.fCheckUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fCheckUserCompleted(this, new fCheckUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.sky3a.hiware.ru#wsSky:fPacientListPage", RequestNamespace="www.sky3a.hiware.ru", ResponseNamespace="www.sky3a.hiware.ru", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public otPacientListPage fPacientListPage(string vUserRef, int vPageNum, int vRowsPerPage, int vOrderField, string vSearchText, int vSearchField, string vDate1, string vDate2) {
            object[] results = this.Invoke("fPacientListPage", new object[] {
                        vUserRef,
                        vPageNum,
                        vRowsPerPage,
                        vOrderField,
                        vSearchText,
                        vSearchField,
                        vDate1,
                        vDate2});
            return ((otPacientListPage)(results[0]));
        }
        
        /// <remarks/>
        public void fPacientListPageAsync(string vUserRef, int vPageNum, int vRowsPerPage, int vOrderField, string vSearchText, int vSearchField, string vDate1, string vDate2) {
            this.fPacientListPageAsync(vUserRef, vPageNum, vRowsPerPage, vOrderField, vSearchText, vSearchField, vDate1, vDate2, null);
        }
        
        /// <remarks/>
        public void fPacientListPageAsync(string vUserRef, int vPageNum, int vRowsPerPage, int vOrderField, string vSearchText, int vSearchField, string vDate1, string vDate2, object userState) {
            if ((this.fPacientListPageOperationCompleted == null)) {
                this.fPacientListPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfPacientListPageOperationCompleted);
            }
            this.InvokeAsync("fPacientListPage", new object[] {
                        vUserRef,
                        vPageNum,
                        vRowsPerPage,
                        vOrderField,
                        vSearchText,
                        vSearchField,
                        vDate1,
                        vDate2}, this.fPacientListPageOperationCompleted, userState);
        }
        
        private void OnfPacientListPageOperationCompleted(object arg) {
            if ((this.fPacientListPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fPacientListPageCompleted(this, new fPacientListPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.sky3a.hiware.ru#wsSky:fTemplateShow", RequestNamespace="www.sky3a.hiware.ru", ResponseNamespace="www.sky3a.hiware.ru", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public otTemplateShow fTemplateShow(string vUserRef, string vTemplateRef) {
            object[] results = this.Invoke("fTemplateShow", new object[] {
                        vUserRef,
                        vTemplateRef});
            return ((otTemplateShow)(results[0]));
        }
        
        /// <remarks/>
        public void fTemplateShowAsync(string vUserRef, string vTemplateRef) {
            this.fTemplateShowAsync(vUserRef, vTemplateRef, null);
        }
        
        /// <remarks/>
        public void fTemplateShowAsync(string vUserRef, string vTemplateRef, object userState) {
            if ((this.fTemplateShowOperationCompleted == null)) {
                this.fTemplateShowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfTemplateShowOperationCompleted);
            }
            this.InvokeAsync("fTemplateShow", new object[] {
                        vUserRef,
                        vTemplateRef}, this.fTemplateShowOperationCompleted, userState);
        }
        
        private void OnfTemplateShowOperationCompleted(object arg) {
            if ((this.fTemplateShowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fTemplateShowCompleted(this, new fTemplateShowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.sky3a.hiware.ru#wsSky:fTamplateListPage1", RequestNamespace="www.sky3a.hiware.ru", ResponseNamespace="www.sky3a.hiware.ru", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public otServiceListPage fTamplateListPage1(string vUserRef, int vPageNum, int vRowsPerPage, string vPacientRef, string vDate1, string vDate2) {
            object[] results = this.Invoke("fTamplateListPage1", new object[] {
                        vUserRef,
                        vPageNum,
                        vRowsPerPage,
                        vPacientRef,
                        vDate1,
                        vDate2});
            return ((otServiceListPage)(results[0]));
        }
        
        /// <remarks/>
        public void fTamplateListPage1Async(string vUserRef, int vPageNum, int vRowsPerPage, string vPacientRef, string vDate1, string vDate2) {
            this.fTamplateListPage1Async(vUserRef, vPageNum, vRowsPerPage, vPacientRef, vDate1, vDate2, null);
        }
        
        /// <remarks/>
        public void fTamplateListPage1Async(string vUserRef, int vPageNum, int vRowsPerPage, string vPacientRef, string vDate1, string vDate2, object userState) {
            if ((this.fTamplateListPage1OperationCompleted == null)) {
                this.fTamplateListPage1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnfTamplateListPage1OperationCompleted);
            }
            this.InvokeAsync("fTamplateListPage1", new object[] {
                        vUserRef,
                        vPageNum,
                        vRowsPerPage,
                        vPacientRef,
                        vDate1,
                        vDate2}, this.fTamplateListPage1OperationCompleted, userState);
        }
        
        private void OnfTamplateListPage1OperationCompleted(object arg) {
            if ((this.fTamplateListPage1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fTamplateListPage1Completed(this, new fTamplateListPage1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.sky3a.hiware.ru#wsSky:fObjectListPage", RequestNamespace="www.sky3a.hiware.ru", ResponseNamespace="www.sky3a.hiware.ru", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public otObjectList fObjectListPage(string vUserRef, otAnyActionData vAnyActionData) {
            object[] results = this.Invoke("fObjectListPage", new object[] {
                        vUserRef,
                        vAnyActionData});
            return ((otObjectList)(results[0]));
        }
        
        /// <remarks/>
        public void fObjectListPageAsync(string vUserRef, otAnyActionData vAnyActionData) {
            this.fObjectListPageAsync(vUserRef, vAnyActionData, null);
        }
        
        /// <remarks/>
        public void fObjectListPageAsync(string vUserRef, otAnyActionData vAnyActionData, object userState) {
            if ((this.fObjectListPageOperationCompleted == null)) {
                this.fObjectListPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfObjectListPageOperationCompleted);
            }
            this.InvokeAsync("fObjectListPage", new object[] {
                        vUserRef,
                        vAnyActionData}, this.fObjectListPageOperationCompleted, userState);
        }
        
        private void OnfObjectListPageOperationCompleted(object arg) {
            if ((this.fObjectListPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fObjectListPageCompleted(this, new fObjectListPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otTicketListPage {
        
        private otRespHeader prRespHeaderField;
        
        private int prRecordCountField;
        
        private int prPageCountField;
        
        private otTicketListRow[] prTicketListRowsField;
        
        /// <remarks/>
        public otRespHeader prRespHeader {
            get {
                return this.prRespHeaderField;
            }
            set {
                this.prRespHeaderField = value;
            }
        }
        
        /// <remarks/>
        public int prRecordCount {
            get {
                return this.prRecordCountField;
            }
            set {
                this.prRecordCountField = value;
            }
        }
        
        /// <remarks/>
        public int prPageCount {
            get {
                return this.prPageCountField;
            }
            set {
                this.prPageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("prTicketListRow", IsNullable=false)]
        public otTicketListRow[] prTicketListRows {
            get {
                return this.prTicketListRowsField;
            }
            set {
                this.prTicketListRowsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otRespHeader {
        
        private int prRespResultField;
        
        private string prRespMessageField;
        
        private int prRespMessagePosField;
        
        private string prRespInfoField;
        
        /// <remarks/>
        public int prRespResult {
            get {
                return this.prRespResultField;
            }
            set {
                this.prRespResultField = value;
            }
        }
        
        /// <remarks/>
        public string prRespMessage {
            get {
                return this.prRespMessageField;
            }
            set {
                this.prRespMessageField = value;
            }
        }
        
        /// <remarks/>
        public int prRespMessagePos {
            get {
                return this.prRespMessagePosField;
            }
            set {
                this.prRespMessagePosField = value;
            }
        }
        
        /// <remarks/>
        public string prRespInfo {
            get {
                return this.prRespInfoField;
            }
            set {
                this.prRespInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otObjectRow {
        
        private string prParam1Field;
        
        private string prParam2Field;
        
        private string prParam3Field;
        
        private string prParam4Field;
        
        private string prParam5Field;
        
        private string prParam6Field;
        
        private string prParam7Field;
        
        private string prParam8Field;
        
        private string prParam9Field;
        
        private string prParam10Field;
        
        private string prParam11Field;
        
        private string prParam12Field;
        
        /// <remarks/>
        public string prParam1 {
            get {
                return this.prParam1Field;
            }
            set {
                this.prParam1Field = value;
            }
        }
        
        /// <remarks/>
        public string prParam2 {
            get {
                return this.prParam2Field;
            }
            set {
                this.prParam2Field = value;
            }
        }
        
        /// <remarks/>
        public string prParam3 {
            get {
                return this.prParam3Field;
            }
            set {
                this.prParam3Field = value;
            }
        }
        
        /// <remarks/>
        public string prParam4 {
            get {
                return this.prParam4Field;
            }
            set {
                this.prParam4Field = value;
            }
        }
        
        /// <remarks/>
        public string prParam5 {
            get {
                return this.prParam5Field;
            }
            set {
                this.prParam5Field = value;
            }
        }
        
        /// <remarks/>
        public string prParam6 {
            get {
                return this.prParam6Field;
            }
            set {
                this.prParam6Field = value;
            }
        }
        
        /// <remarks/>
        public string prParam7 {
            get {
                return this.prParam7Field;
            }
            set {
                this.prParam7Field = value;
            }
        }
        
        /// <remarks/>
        public string prParam8 {
            get {
                return this.prParam8Field;
            }
            set {
                this.prParam8Field = value;
            }
        }
        
        /// <remarks/>
        public string prParam9 {
            get {
                return this.prParam9Field;
            }
            set {
                this.prParam9Field = value;
            }
        }
        
        /// <remarks/>
        public string prParam10 {
            get {
                return this.prParam10Field;
            }
            set {
                this.prParam10Field = value;
            }
        }
        
        /// <remarks/>
        public string prParam11 {
            get {
                return this.prParam11Field;
            }
            set {
                this.prParam11Field = value;
            }
        }
        
        /// <remarks/>
        public string prParam12 {
            get {
                return this.prParam12Field;
            }
            set {
                this.prParam12Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otObjectList {
        
        private otRespHeader prRespHeaderField;
        
        private int prRecordCountField;
        
        private int prPageCountField;
        
        private otAnyActionParam[] prAnyActionParamsField;
        
        private otObjectRow[] prObjectRowsField;
        
        /// <remarks/>
        public otRespHeader prRespHeader {
            get {
                return this.prRespHeaderField;
            }
            set {
                this.prRespHeaderField = value;
            }
        }
        
        /// <remarks/>
        public int prRecordCount {
            get {
                return this.prRecordCountField;
            }
            set {
                this.prRecordCountField = value;
            }
        }
        
        /// <remarks/>
        public int prPageCount {
            get {
                return this.prPageCountField;
            }
            set {
                this.prPageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("prAnyActionParam", IsNullable=false)]
        public otAnyActionParam[] prAnyActionParams {
            get {
                return this.prAnyActionParamsField;
            }
            set {
                this.prAnyActionParamsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("prObjectRow", IsNullable=false)]
        public otObjectRow[] prObjectRows {
            get {
                return this.prObjectRowsField;
            }
            set {
                this.prObjectRowsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otAnyActionParam {
        
        private string prNameField;
        
        private string prValueField;
        
        /// <remarks/>
        public string prName {
            get {
                return this.prNameField;
            }
            set {
                this.prNameField = value;
            }
        }
        
        /// <remarks/>
        public string prValue {
            get {
                return this.prValueField;
            }
            set {
                this.prValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otTemplParam {
        
        private string prRefField;
        
        private string prRowNumField;
        
        private string prNameField;
        
        private string prCaptionField;
        
        private string prDataTypeField;
        
        private string prPermissField;
        
        private string prValueField;
        
        private string prCreateDateField;
        
        private string prCreateUserField;
        
        /// <remarks/>
        public string prRef {
            get {
                return this.prRefField;
            }
            set {
                this.prRefField = value;
            }
        }
        
        /// <remarks/>
        public string prRowNum {
            get {
                return this.prRowNumField;
            }
            set {
                this.prRowNumField = value;
            }
        }
        
        /// <remarks/>
        public string prName {
            get {
                return this.prNameField;
            }
            set {
                this.prNameField = value;
            }
        }
        
        /// <remarks/>
        public string prCaption {
            get {
                return this.prCaptionField;
            }
            set {
                this.prCaptionField = value;
            }
        }
        
        /// <remarks/>
        public string prDataType {
            get {
                return this.prDataTypeField;
            }
            set {
                this.prDataTypeField = value;
            }
        }
        
        /// <remarks/>
        public string prPermiss {
            get {
                return this.prPermissField;
            }
            set {
                this.prPermissField = value;
            }
        }
        
        /// <remarks/>
        public string prValue {
            get {
                return this.prValueField;
            }
            set {
                this.prValueField = value;
            }
        }
        
        /// <remarks/>
        public string prCreateDate {
            get {
                return this.prCreateDateField;
            }
            set {
                this.prCreateDateField = value;
            }
        }
        
        /// <remarks/>
        public string prCreateUser {
            get {
                return this.prCreateUserField;
            }
            set {
                this.prCreateUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otTemplateShow {
        
        private otRespHeader prRespHeaderField;
        
        private int prParamCountField;
        
        private string prTemplateRefField;
        
        private string prTemplateNameField;
        
        private string prCreateDateField;
        
        private string prCreateUserField;
        
        private string prCaptionField;
        
        private otTemplParam[] prTemplParamListField;
        
        /// <remarks/>
        public otRespHeader prRespHeader {
            get {
                return this.prRespHeaderField;
            }
            set {
                this.prRespHeaderField = value;
            }
        }
        
        /// <remarks/>
        public int prParamCount {
            get {
                return this.prParamCountField;
            }
            set {
                this.prParamCountField = value;
            }
        }
        
        /// <remarks/>
        public string prTemplateRef {
            get {
                return this.prTemplateRefField;
            }
            set {
                this.prTemplateRefField = value;
            }
        }
        
        /// <remarks/>
        public string prTemplateName {
            get {
                return this.prTemplateNameField;
            }
            set {
                this.prTemplateNameField = value;
            }
        }
        
        /// <remarks/>
        public string prCreateDate {
            get {
                return this.prCreateDateField;
            }
            set {
                this.prCreateDateField = value;
            }
        }
        
        /// <remarks/>
        public string prCreateUser {
            get {
                return this.prCreateUserField;
            }
            set {
                this.prCreateUserField = value;
            }
        }
        
        /// <remarks/>
        public string prCaption {
            get {
                return this.prCaptionField;
            }
            set {
                this.prCaptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("prTemplParam", IsNullable=false)]
        public otTemplParam[] prTemplParamList {
            get {
                return this.prTemplParamListField;
            }
            set {
                this.prTemplParamListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otPacientListRow {
        
        private string prPacientRefField;
        
        private string prFIOField;
        
        private string prDateBirthField;
        
        private string prPhoneNumberField;
        
        private string prCreateDateField;
        
        private string prDateLastField;
        
        /// <remarks/>
        public string prPacientRef {
            get {
                return this.prPacientRefField;
            }
            set {
                this.prPacientRefField = value;
            }
        }
        
        /// <remarks/>
        public string prFIO {
            get {
                return this.prFIOField;
            }
            set {
                this.prFIOField = value;
            }
        }
        
        /// <remarks/>
        public string prDateBirth {
            get {
                return this.prDateBirthField;
            }
            set {
                this.prDateBirthField = value;
            }
        }
        
        /// <remarks/>
        public string prPhoneNumber {
            get {
                return this.prPhoneNumberField;
            }
            set {
                this.prPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string prCreateDate {
            get {
                return this.prCreateDateField;
            }
            set {
                this.prCreateDateField = value;
            }
        }
        
        /// <remarks/>
        public string prDateLast {
            get {
                return this.prDateLastField;
            }
            set {
                this.prDateLastField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otPacientListPage {
        
        private otRespHeader prRespHeaderField;
        
        private int prRecordCountField;
        
        private int prPageCountField;
        
        private otPacientListRow[] prPacientListRowsField;
        
        /// <remarks/>
        public otRespHeader prRespHeader {
            get {
                return this.prRespHeaderField;
            }
            set {
                this.prRespHeaderField = value;
            }
        }
        
        /// <remarks/>
        public int prRecordCount {
            get {
                return this.prRecordCountField;
            }
            set {
                this.prRecordCountField = value;
            }
        }
        
        /// <remarks/>
        public int prPageCount {
            get {
                return this.prPageCountField;
            }
            set {
                this.prPageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("prPacientListRow", IsNullable=false)]
        public otPacientListRow[] prPacientListRows {
            get {
                return this.prPacientListRowsField;
            }
            set {
                this.prPacientListRowsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otCheckUser {
        
        private otRespHeader prRespHeaderField;
        
        private string prUserRefField;
        
        /// <remarks/>
        public otRespHeader prRespHeader {
            get {
                return this.prRespHeaderField;
            }
            set {
                this.prRespHeaderField = value;
            }
        }
        
        /// <remarks/>
        public string prUserRef {
            get {
                return this.prUserRefField;
            }
            set {
                this.prUserRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otShowUserInfo {
        
        private otRespHeader prRespHeaderField;
        
        private string prUserNameField;
        
        private int prIsGuestField;
        
        private string prCompanyNameField;
        
        private string prLastEventDateField;
        
        private string prLastEventField;
        
        private int prLastEventStyleField;
        
        private string prUploadPathField;
        
        private string prPacientLinkTextField;
        
        /// <remarks/>
        public otRespHeader prRespHeader {
            get {
                return this.prRespHeaderField;
            }
            set {
                this.prRespHeaderField = value;
            }
        }
        
        /// <remarks/>
        public string prUserName {
            get {
                return this.prUserNameField;
            }
            set {
                this.prUserNameField = value;
            }
        }
        
        /// <remarks/>
        public int prIsGuest {
            get {
                return this.prIsGuestField;
            }
            set {
                this.prIsGuestField = value;
            }
        }
        
        /// <remarks/>
        public string prCompanyName {
            get {
                return this.prCompanyNameField;
            }
            set {
                this.prCompanyNameField = value;
            }
        }
        
        /// <remarks/>
        public string prLastEventDate {
            get {
                return this.prLastEventDateField;
            }
            set {
                this.prLastEventDateField = value;
            }
        }
        
        /// <remarks/>
        public string prLastEvent {
            get {
                return this.prLastEventField;
            }
            set {
                this.prLastEventField = value;
            }
        }
        
        /// <remarks/>
        public int prLastEventStyle {
            get {
                return this.prLastEventStyleField;
            }
            set {
                this.prLastEventStyleField = value;
            }
        }
        
        /// <remarks/>
        public string prUploadPath {
            get {
                return this.prUploadPathField;
            }
            set {
                this.prUploadPathField = value;
            }
        }
        
        /// <remarks/>
        public string prPacientLinkText {
            get {
                return this.prPacientLinkTextField;
            }
            set {
                this.prPacientLinkTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otAnyActionData {
        
        private int prWSIDField;
        
        private otAnyActionParam[] prAnyActionParamsField;
        
        /// <remarks/>
        public int prWSID {
            get {
                return this.prWSIDField;
            }
            set {
                this.prWSIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("prAnyActionParam", IsNullable=false)]
        public otAnyActionParam[] prAnyActionParams {
            get {
                return this.prAnyActionParamsField;
            }
            set {
                this.prAnyActionParamsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otAnyActionResp {
        
        private otRespHeader prRespHeaderField;
        
        private int prWSIDField;
        
        private otAnyActionParam[] prAnyActionParamsField;
        
        /// <remarks/>
        public otRespHeader prRespHeader {
            get {
                return this.prRespHeaderField;
            }
            set {
                this.prRespHeaderField = value;
            }
        }
        
        /// <remarks/>
        public int prWSID {
            get {
                return this.prWSIDField;
            }
            set {
                this.prWSIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("prAnyActionParam", IsNullable=false)]
        public otAnyActionParam[] prAnyActionParams {
            get {
                return this.prAnyActionParamsField;
            }
            set {
                this.prAnyActionParamsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otParamValueEdit {
        
        private string prRefField;
        
        private string prValueField;
        
        private int prEditedField;
        
        /// <remarks/>
        public string prRef {
            get {
                return this.prRefField;
            }
            set {
                this.prRefField = value;
            }
        }
        
        /// <remarks/>
        public string prValue {
            get {
                return this.prValueField;
            }
            set {
                this.prValueField = value;
            }
        }
        
        /// <remarks/>
        public int prEdited {
            get {
                return this.prEditedField;
            }
            set {
                this.prEditedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otParamValueShow {
        
        private string prRefField;
        
        private string prNameField;
        
        private string prCaptionField;
        
        private string prDataTypeField;
        
        private string prPermissField;
        
        private string prValueField;
        
        /// <remarks/>
        public string prRef {
            get {
                return this.prRefField;
            }
            set {
                this.prRefField = value;
            }
        }
        
        /// <remarks/>
        public string prName {
            get {
                return this.prNameField;
            }
            set {
                this.prNameField = value;
            }
        }
        
        /// <remarks/>
        public string prCaption {
            get {
                return this.prCaptionField;
            }
            set {
                this.prCaptionField = value;
            }
        }
        
        /// <remarks/>
        public string prDataType {
            get {
                return this.prDataTypeField;
            }
            set {
                this.prDataTypeField = value;
            }
        }
        
        /// <remarks/>
        public string prPermiss {
            get {
                return this.prPermissField;
            }
            set {
                this.prPermissField = value;
            }
        }
        
        /// <remarks/>
        public string prValue {
            get {
                return this.prValueField;
            }
            set {
                this.prValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otServiceShow {
        
        private otRespHeader prRespHeaderField;
        
        private int prParamCountField;
        
        private string prServiceRefField;
        
        private string prServiceNumField;
        
        private string prDateField;
        
        private string prTimeField;
        
        private string prPacientField;
        
        private string prUserNameField;
        
        private string prCaptionField;
        
        private otParamValueShow[] prParamValuesShowField;
        
        /// <remarks/>
        public otRespHeader prRespHeader {
            get {
                return this.prRespHeaderField;
            }
            set {
                this.prRespHeaderField = value;
            }
        }
        
        /// <remarks/>
        public int prParamCount {
            get {
                return this.prParamCountField;
            }
            set {
                this.prParamCountField = value;
            }
        }
        
        /// <remarks/>
        public string prServiceRef {
            get {
                return this.prServiceRefField;
            }
            set {
                this.prServiceRefField = value;
            }
        }
        
        /// <remarks/>
        public string prServiceNum {
            get {
                return this.prServiceNumField;
            }
            set {
                this.prServiceNumField = value;
            }
        }
        
        /// <remarks/>
        public string prDate {
            get {
                return this.prDateField;
            }
            set {
                this.prDateField = value;
            }
        }
        
        /// <remarks/>
        public string prTime {
            get {
                return this.prTimeField;
            }
            set {
                this.prTimeField = value;
            }
        }
        
        /// <remarks/>
        public string prPacient {
            get {
                return this.prPacientField;
            }
            set {
                this.prPacientField = value;
            }
        }
        
        /// <remarks/>
        public string prUserName {
            get {
                return this.prUserNameField;
            }
            set {
                this.prUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string prCaption {
            get {
                return this.prCaptionField;
            }
            set {
                this.prCaptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("prParamValueShow", IsNullable=false)]
        public otParamValueShow[] prParamValuesShow {
            get {
                return this.prParamValuesShowField;
            }
            set {
                this.prParamValuesShowField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otServiceListRow {
        
        private string prServiceRefField;
        
        private string prServiceNumField;
        
        private string prDateField;
        
        private string prTimeField;
        
        private string prPacientRefField;
        
        private string prPacientField;
        
        private string prUserNameField;
        
        private string prCaptionField;
        
        /// <remarks/>
        public string prServiceRef {
            get {
                return this.prServiceRefField;
            }
            set {
                this.prServiceRefField = value;
            }
        }
        
        /// <remarks/>
        public string prServiceNum {
            get {
                return this.prServiceNumField;
            }
            set {
                this.prServiceNumField = value;
            }
        }
        
        /// <remarks/>
        public string prDate {
            get {
                return this.prDateField;
            }
            set {
                this.prDateField = value;
            }
        }
        
        /// <remarks/>
        public string prTime {
            get {
                return this.prTimeField;
            }
            set {
                this.prTimeField = value;
            }
        }
        
        /// <remarks/>
        public string prPacientRef {
            get {
                return this.prPacientRefField;
            }
            set {
                this.prPacientRefField = value;
            }
        }
        
        /// <remarks/>
        public string prPacient {
            get {
                return this.prPacientField;
            }
            set {
                this.prPacientField = value;
            }
        }
        
        /// <remarks/>
        public string prUserName {
            get {
                return this.prUserNameField;
            }
            set {
                this.prUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string prCaption {
            get {
                return this.prCaptionField;
            }
            set {
                this.prCaptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otServiceListPage {
        
        private otRespHeader prRespHeaderField;
        
        private int prRecordCountField;
        
        private int prPageCountField;
        
        private otServiceListRow[] prServiceListRowsField;
        
        /// <remarks/>
        public otRespHeader prRespHeader {
            get {
                return this.prRespHeaderField;
            }
            set {
                this.prRespHeaderField = value;
            }
        }
        
        /// <remarks/>
        public int prRecordCount {
            get {
                return this.prRecordCountField;
            }
            set {
                this.prRecordCountField = value;
            }
        }
        
        /// <remarks/>
        public int prPageCount {
            get {
                return this.prPageCountField;
            }
            set {
                this.prPageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("prServiceListRow", IsNullable=false)]
        public otServiceListRow[] prServiceListRows {
            get {
                return this.prServiceListRowsField;
            }
            set {
                this.prServiceListRowsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otTicketShowService {
        
        private string prServiceRefField;
        
        private string prServiceNumField;
        
        private string prDateField;
        
        private string prTimeField;
        
        private string prUserNameField;
        
        private string prCaptionField;
        
        /// <remarks/>
        public string prServiceRef {
            get {
                return this.prServiceRefField;
            }
            set {
                this.prServiceRefField = value;
            }
        }
        
        /// <remarks/>
        public string prServiceNum {
            get {
                return this.prServiceNumField;
            }
            set {
                this.prServiceNumField = value;
            }
        }
        
        /// <remarks/>
        public string prDate {
            get {
                return this.prDateField;
            }
            set {
                this.prDateField = value;
            }
        }
        
        /// <remarks/>
        public string prTime {
            get {
                return this.prTimeField;
            }
            set {
                this.prTimeField = value;
            }
        }
        
        /// <remarks/>
        public string prUserName {
            get {
                return this.prUserNameField;
            }
            set {
                this.prUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string prCaption {
            get {
                return this.prCaptionField;
            }
            set {
                this.prCaptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otTicketShow {
        
        private otRespHeader prRespHeaderField;
        
        private int prServiceCountField;
        
        private string prTicketRefField;
        
        private string prTicketNumField;
        
        private string prDateField;
        
        private string prTimeField;
        
        private string prPacientField;
        
        private string prUserNameField;
        
        private string prCaptionField;
        
        private otTicketShowService[] prTicketServicesField;
        
        /// <remarks/>
        public otRespHeader prRespHeader {
            get {
                return this.prRespHeaderField;
            }
            set {
                this.prRespHeaderField = value;
            }
        }
        
        /// <remarks/>
        public int prServiceCount {
            get {
                return this.prServiceCountField;
            }
            set {
                this.prServiceCountField = value;
            }
        }
        
        /// <remarks/>
        public string prTicketRef {
            get {
                return this.prTicketRefField;
            }
            set {
                this.prTicketRefField = value;
            }
        }
        
        /// <remarks/>
        public string prTicketNum {
            get {
                return this.prTicketNumField;
            }
            set {
                this.prTicketNumField = value;
            }
        }
        
        /// <remarks/>
        public string prDate {
            get {
                return this.prDateField;
            }
            set {
                this.prDateField = value;
            }
        }
        
        /// <remarks/>
        public string prTime {
            get {
                return this.prTimeField;
            }
            set {
                this.prTimeField = value;
            }
        }
        
        /// <remarks/>
        public string prPacient {
            get {
                return this.prPacientField;
            }
            set {
                this.prPacientField = value;
            }
        }
        
        /// <remarks/>
        public string prUserName {
            get {
                return this.prUserNameField;
            }
            set {
                this.prUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string prCaption {
            get {
                return this.prCaptionField;
            }
            set {
                this.prCaptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("prTicketShowService", IsNullable=false)]
        public otTicketShowService[] prTicketServices {
            get {
                return this.prTicketServicesField;
            }
            set {
                this.prTicketServicesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.sky3a.hiware.ru")]
    public partial class otTicketListRow {
        
        private string prTicketRefField;
        
        private string prTicketNumField;
        
        private string prDateField;
        
        private string prTimeField;
        
        private string prPacientField;
        
        private string prUserNameField;
        
        private string prCaptionField;
        
        /// <remarks/>
        public string prTicketRef {
            get {
                return this.prTicketRefField;
            }
            set {
                this.prTicketRefField = value;
            }
        }
        
        /// <remarks/>
        public string prTicketNum {
            get {
                return this.prTicketNumField;
            }
            set {
                this.prTicketNumField = value;
            }
        }
        
        /// <remarks/>
        public string prDate {
            get {
                return this.prDateField;
            }
            set {
                this.prDateField = value;
            }
        }
        
        /// <remarks/>
        public string prTime {
            get {
                return this.prTimeField;
            }
            set {
                this.prTimeField = value;
            }
        }
        
        /// <remarks/>
        public string prPacient {
            get {
                return this.prPacientField;
            }
            set {
                this.prPacientField = value;
            }
        }
        
        /// <remarks/>
        public string prUserName {
            get {
                return this.prUserNameField;
            }
            set {
                this.prUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string prCaption {
            get {
                return this.prCaptionField;
            }
            set {
                this.prCaptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void fTicketListPageCompletedEventHandler(object sender, fTicketListPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fTicketListPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fTicketListPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public otTicketListPage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((otTicketListPage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void fTicketShowCompletedEventHandler(object sender, fTicketShowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fTicketShowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fTicketShowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public otTicketShow Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((otTicketShow)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void fServiceListPageCompletedEventHandler(object sender, fServiceListPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fServiceListPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fServiceListPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public otServiceListPage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((otServiceListPage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void fServiceShowCompletedEventHandler(object sender, fServiceShowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fServiceShowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fServiceShowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public otServiceShow Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((otServiceShow)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void fServiceEditCompletedEventHandler(object sender, fServiceEditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fServiceEditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fServiceEditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public otAnyActionResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((otAnyActionResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void fAnyActionCompletedEventHandler(object sender, fAnyActionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fAnyActionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fAnyActionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public otAnyActionResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((otAnyActionResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void fShowUserInfoCompletedEventHandler(object sender, fShowUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fShowUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fShowUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public otShowUserInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((otShowUserInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void fCheckUserCompletedEventHandler(object sender, fCheckUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fCheckUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fCheckUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public otCheckUser Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((otCheckUser)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void fPacientListPageCompletedEventHandler(object sender, fPacientListPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fPacientListPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fPacientListPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public otPacientListPage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((otPacientListPage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void fTemplateShowCompletedEventHandler(object sender, fTemplateShowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fTemplateShowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fTemplateShowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public otTemplateShow Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((otTemplateShow)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void fTamplateListPage1CompletedEventHandler(object sender, fTamplateListPage1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fTamplateListPage1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fTamplateListPage1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public otServiceListPage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((otServiceListPage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void fObjectListPageCompletedEventHandler(object sender, fObjectListPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fObjectListPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fObjectListPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public otObjectList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((otObjectList)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591